Vagrant.configure("2") do |config|
  N = 1
  (1..N).each do |i|  
    config.vm.define "web#{i}" do |node|
      node.vm.box = "bento/ubuntu-24.04"
      node.vm.hostname = "web#{i}"
      node.vm.network "private_network", ip: "192.168.122.10#{i}"
      node.vm.network "forwarded_port", guest: 80, host: "8080"
      node.vm.synced_folder ".", "/vagrant"
      node.vm.provider :libvirt do |libvirt|
        libvirt.cpus = "2"
        libvirt.memory = "2048"
      end
    end
    config.vm.define "log#{i}" do |node|
      node.vm.box = "bento/ubuntu-24.04"
      node.vm.hostname = "log#{i}"
      node.vm.network "private_network", ip: "192.168.122.20#{i}"
      node.vm.network "forwarded_port", guest: 80, host: "8080"
      node.vm.synced_folder ".", "/vagrant"
      node.vm.provider :libvirt do |libvirt|
        libvirt.cpus = "2"
        libvirt.memory = "2048"
      end
      if i == N
        config.vm.provision "ansible" do |ansible|
          ansible.playbook = "provision.yml"
        end    
      end
    end
  end
end

