Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04" 
  config.vm.define "server" do |server| 
    server.vm.hostname = "server" 
    server.vm.network "private_network", ip: "192.168.56.10" 
  end 
  config.vm.define "client" do |client| 
    client.vm.hostname = "client" 
    client.vm.network "private_network", ip: "192.168.56.20" 
    client.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/provision.yml"
      ansible.inventory_path = "ansible/hosts"
      ansible.host_key_checking = "false"
      ansible.limit = "all"
    end
  end
end
