# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :master => {
        :box_name => "bento/centos-stream-9",
        :vm_name => "master",
        :ip_addr => '192.168.11.150'
  },
  :slave => {
        :box_name => "bento/centos-stream-9",
        :vm_name => "slave",
        :ip_addr => '192.168.11.151'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
          end

          box.vm.provision :shell do |s|
             s.inline = 'mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh'
          end
          if boxconfig[:vm_name] == "slave"
            box.vm.provision "ansible" do |ansible|
              ansible.playbook = "provision.yml"
              ansible.inventory_path = "hosts"
              ansible.host_key_checking = "false"
              ansible.become = "true"
              ansible.limit = "all"
            end
          end
      end
  end
end
